version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my webpage"
    - zip -r webpage.zip *
  post_build:
    commands:
    - echo "Deployed to S3"
artifacts:
  type: zip
  paths:
    - '*'
